const fs=require('fs');
const path=require('path');
const OUT=path.join(process.cwd(),'dist');

function walk(dir,cb){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full,cb);else if(/\.html$/i.test(entry.name))cb(full);}}

const CSS=`<style id="rf-design-atelier">
:root{--at-ink:#24180f;--at-muted:#7a6657;--at-orange:#e95808;--at-orange-soft:#fff0df;--at-paper:#fffdf9;--at-sand:#f7ecdf;--at-line:rgba(111,72,42,.13);--at-shadow:0 22px 58px rgba(65,35,16,.11)}
html{background:var(--at-paper)}body{background:radial-gradient(circle at 92% 8%,rgba(249,183,112,.20),transparent 23rem),linear-gradient(180deg,#fffdf9 0%,#fbf1e6 50%,#fffdf9 100%)!important;color:var(--at-ink)!important}body:after{display:none!important}
header{background:rgba(255,253,249,.94)!important;border-bottom:1px solid var(--at-line)!important;box-shadow:0 10px 30px rgba(70,37,14,.055)!important;backdrop-filter:blur(18px) saturate(125%)!important}header .mx-auto{max-width:1240px!important}header a:first-child:after{display:none!important}header nav{border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;gap:4px!important}header nav a{position:relative;border-radius:11px!important;color:#654c3c!important;font-weight:780!important}header nav a:not(:last-child):after{content:"";position:absolute;left:12px;right:12px;bottom:4px;height:2px;border-radius:9px;background:var(--at-orange);transform:scaleX(0);transform-origin:left;transition:transform .22s ease}header nav a:not(:last-child):hover{background:transparent!important;color:var(--at-ink)!important}header nav a:not(:last-child):hover:after{transform:scaleX(1)}header nav a:last-child{border-radius:999px!important;background:linear-gradient(135deg,#f77a21,#e34c05)!important;box-shadow:0 10px 20px rgba(207,65,1,.22)!important}
h1{font-family:Georgia,"Times New Roman",serif!important;font-weight:700!important;letter-spacing:-.055em!important;color:#2d190c!important}h2{font-weight:900!important;letter-spacing:-.038em!important;color:#2d190c!important}h3{font-weight:850!important;color:#994005!important}p{color:var(--at-muted)!important}
#view-home>section:first-child{background:linear-gradient(115deg,#fffdf9 0%,#fff7ef 54%,#fbe8d3 100%)!important}#view-home>section:first-child:before{opacity:.075!important;filter:blur(5px)!important}#view-home>section:first-child:after{opacity:.19!important;filter:blur(4px)!important}#view-home h1{max-width:14ch!important;font-size:clamp(2.75rem,5.4vw,5rem)!important;line-height:.98!important}#view-home h1:after{width:48px!important;height:4px!important;margin-top:20px!important;background:linear-gradient(90deg,#e95808,#f5a83e)!important}#view-home>section:first-child p{max-width:48ch!important;font-size:1.05rem!important;line-height:1.75!important}
#ruleta:before{inset:-20px!important;opacity:.68!important;filter:blur(22px)!important}#wheel{box-shadow:0 0 0 9px #fffdf9,0 0 0 11px rgba(232,88,8,.18),0 26px 55px rgba(55,25,7,.22)!important}#spinBtn{min-height:58px!important;border-radius:999px!important;background:linear-gradient(135deg,#f57c21,#e65006)!important;box-shadow:0 15px 28px rgba(208,65,0,.27)!important}#spinBtn:after{content:""!important}#spinBtn:hover{transform:translateY(-3px)!important}
.rf-supernova-quick{max-width:1120px!important;transform:translateY(-25px)!important}.rf-supernova-quick-inner{grid-template-columns:1fr auto!important;gap:18px!important;padding:13px 15px 13px 18px!important;border:1px solid rgba(225,187,153,.66)!important;border-radius:18px!important;background:rgba(255,253,249,.90)!important;box-shadow:0 14px 32px rgba(75,38,13,.09)!important}.rf-supernova-status{font-size:.8rem!important;color:#725644!important}.rf-supernova-dot{width:9px!important;height:9px!important;background:#e95808!important;box-shadow:0 0 0 4px rgba(233,88,8,.12)!important}.rf-supernova-actions a{min-height:35px!important;border:0!important;border-radius:10px!important;background:transparent!important;box-shadow:none!important;color:#654b3a!important;font-size:.75rem!important}.rf-supernova-actions a:hover{background:var(--at-orange-soft)!important;color:#b34203!important;transform:none!important;box-shadow:none!important}.rf-supernova-actions a b{width:18px!important;height:18px!important;border-radius:6px!important;background:#f2dfce!important;color:#b44204!important}
#home-explore>div,.seo-hub{border:1px solid var(--at-line)!important;border-radius:28px!important;background:rgba(255,253,249,.78)!important;box-shadow:var(--at-shadow)!important}#home-explore>div:before,.seo-hub:before{height:3px!important;background:linear-gradient(90deg,#ed5b0a,#f2a23f 45%,rgba(242,162,63,.16) 76%)!important}#home-explore a,.seo-card{border:1px solid rgba(225,197,176,.70)!important;border-radius:18px!important;background:#fffdf9!important;box-shadow:none!important}#home-explore a:after,.seo-card:after{display:none!important}#home-explore a:before,.seo-card:before{height:3px!important;background:linear-gradient(90deg,#ed5b0a,#f0a041)!important;opacity:.82!important}#home-explore a:hover,.seo-card:hover{transform:translateY(-4px)!important;box-shadow:0 17px 26px rgba(75,38,13,.10)!important;border-color:rgba(230,139,72,.52)!important}
main :is(article,.article-content,.page-content .content){border:1px solid var(--at-line)!important;border-radius:26px!important;background:rgba(255,254,251,.92)!important;box-shadow:var(--at-shadow)!important}main :is(article,.article-content,.page-content .content):before{right:22px!important;padding:6px 10px!important;border-color:rgba(238,152,76,.52)!important;background:#fff8ee!important;color:#a9460b!important;font-size:9px!important}main article h2{margin-top:2.4em!important}main article h2:before{width:44px!important;height:4px!important;margin-bottom:12px!important;background:linear-gradient(90deg,#e95808,#f0ae56)!important}main details{border-color:rgba(222,193,171,.75)!important;border-radius:15px!important;background:#fffdfa!important;box-shadow:none!important}main details[open]{border-color:rgba(231,135,63,.52)!important;box-shadow:0 11px 22px rgba(75,38,13,.07)!important}.rf-guide-note{border-left-color:#e95808!important;background:#fff7ed!important;color:#70533d!important}
.rf-decision-cta{max-width:1120px!important}.rf-decision-cta-inner{border:1px solid rgba(255,201,126,.48)!important;border-radius:28px!important;background:linear-gradient(120deg,#351c10,#78320e 60%,#bf4507)!important;box-shadow:0 24px 46px rgba(75,31,7,.20)!important}.rf-decision-cta-inner:after{display:none!important}.rf-decision-cta h2{font-family:Georgia,"Times New Roman",serif!important;font-weight:700!important;letter-spacing:-.045em!important}.rf-decision-cta p:not(.rf-decision-cta-kicker){color:rgba(255,247,239,.78)!important}
.rf-supernova-dock,.rf-supernova-top{display:none!important}.rf-share-float{bottom:22px!important;right:22px!important}.rf-final-footer{padding-bottom:0!important;background:radial-gradient(circle at 88% 0%,rgba(224,98,20,.24),transparent 22rem),linear-gradient(135deg,#26170f,#100a07)!important}.rf-final-footer:after{display:none!important}.rf-footer-inner{max-width:1120px!important}.rf-footer-brand strong{font-family:Georgia,"Times New Roman",serif!important;font-size:1.55rem!important;font-weight:700!important}.rf-footer-brand p{color:#d8c2b2!important}
@media(max-width:767px){header .mx-auto{padding:8px 13px!important}header nav a{font-size:.78rem!important;padding:7px 8px!important}header nav a:last-child{padding-inline:13px!important}.rf-supernova-quick{transform:translateY(-17px)!important}.rf-supernova-quick-inner{display:block!important;padding:12px 13px!important;border-radius:16px!important}.rf-supernova-actions{margin-top:8px!important}.rf-supernova-actions a{padding:0 8px!important;min-height:31px!important}.rf-share-float{bottom:16px!important;right:16px!important}.rf-final-footer{padding-bottom:20px!important}}
</style>`;

let count=0;walk(OUT,file=>{let html=fs.readFileSync(file,'utf8');html=html.replace(/<style id="rf-design-atelier">[\s\S]*?<\/style>/i,'');html=html.replace(/<nav class="rf-supernova-dock"[\s\S]*?<\/nav>\s*/i,'');html=html.replace(/<button class="rf-supernova-top"[\s\S]*?<\/button>\s*/i,'');if(/<\/head>/i.test(html))html=html.replace(/<\/head>/i,CSS+'</head>');fs.writeFileSync(file,html,'utf8');count++;});
console.log(`Atelier refinement applied to ${count} HTML pages.`);
